___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [7]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [8]:
arr_ones=np.ones(10)
print(arr_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [9]:
arr_fives=5*arr_ones
print(arr_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [10]:
arr_int=np.arange(10, 51)
print(arr_int)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [11]:
arr_even=arr_int[arr_int%2==0]
print(arr_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
arr_9=np.arange(0,9).reshape(3,3)
arr_9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [14]:
arr_identity=np.zeros(9).reshape(3,3)
arr_identity[0,0]=1
arr_identity[1,1]=1
arr_identity[2,2]=1
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [19]:
import random
rand_num=random.uniform(0, 1)
rand_num

0.6500269486968494

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [26]:
rand_arr=np.random.normal(0,100, 25)
rand_arr

array([-1.30382375e+02, -1.62219222e+01,  1.93761586e+02,  9.61794817e+01,
       -3.89257030e+01, -1.49801912e+01, -1.03049679e+02, -6.67352807e+01,
        2.04975773e+02,  7.48465002e+01,  1.91951156e+02, -4.84741345e+01,
       -1.96411582e+01, -6.52194300e-02, -8.03377246e+01,  1.09865223e+02,
       -1.68782978e+01,  5.04543144e+01,  1.05168237e+02, -3.31971205e+01,
       -2.43296441e+01,  1.30415509e+02, -7.83383645e+01, -6.34891379e+01,
        1.09973884e+02])

#### Create the following matrix:

In [28]:
rand_num=np.random.uniform(0, 1, 100).reshape(10, 10)
rand_num

array([[0.10277838, 0.23051546, 0.15493992, 0.38505887, 0.17376407,
        0.62500928, 0.63414057, 0.2009753 , 0.46515385, 0.381289  ],
       [0.72597055, 0.01069064, 0.35068179, 0.1490848 , 0.93010593,
        0.51698875, 0.94335369, 0.5353387 , 0.08997332, 0.40149414],
       [0.18148892, 0.94609601, 0.12104881, 0.1069253 , 0.95956622,
        0.38187954, 0.15232479, 0.39404037, 0.26362794, 0.22623463],
       [0.65337979, 0.53257495, 0.48375208, 0.20658654, 0.90863167,
        0.62094385, 0.89446796, 0.02852777, 0.724495  , 0.38100637],
       [0.18940244, 0.06749116, 0.90137986, 0.83788663, 0.84304463,
        0.72947719, 0.67130297, 0.18152638, 0.43450769, 0.16746774],
       [0.03334764, 0.67584038, 0.31370056, 0.27478158, 0.57895652,
        0.05184718, 0.07209593, 0.28882077, 0.26541738, 0.03158289],
       [0.7142925 , 0.02254087, 0.49001119, 0.0991213 , 0.41169597,
        0.88786251, 0.48631097, 0.7209296 , 0.28753342, 0.81542257],
       [0.07991211, 0.21668533, 0.4938893

#### Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
rand_num=np.random.uniform(0, 1, 20)
rand_num

array([0.89185675, 0.85307667, 0.25538036, 0.53498349, 0.91630397,
       0.89824842, 0.17105692, 0.59624475, 0.35936343, 0.74568633,
       0.08597534, 0.87483729, 0.17106747, 0.14851516, 0.3869231 ,
       0.92256049, 0.42240368, 0.5223677 , 0.617068  , 0.76407023])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [31]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [51]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[:3,1]

array([ 2,  7, 12])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [50]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

In [55]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

# Great Job!